# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    commit-message:
      prefix: "ci(deps)"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Sao_Paulo"
    commit-message:
      prefix: "chore(deps)"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "string-width"
      - dependency-name: "wrap-ansi"
